name: Build Eleventy

# runs each time something is pushed to the 'main' branch
on:
  push:
    branches: [main]

# allow one concurrent deployment
group: "pages"
cancel-in-progress: true


jobs:

  # build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: [18]
      - name: Install dependencies & build
        run: |
          npm ci
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './_site'
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v1